services:
  waf-nginx:
    image: owasp/modsecurity-crs:nginx
    container_name: waf-nginx
    restart: always
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - waf_network
    environment:
      - BACKEND=http://tenant-example:3000
    depends_on:
      - backend-server
      - tenant-example
    volumes:
      - ./modsecurity-crs-nginx/nginx/rules/custom_rules.conf:/etc/nginx/conf.d/custom_rules.conf:ro
      - ./modsecurity-crs-nginx/nginx/conf.d/40-logformat.conf:/etc/nginx/conf.d/40-logformat.conf:ro
      - ./modsecurity-crs-nginx/nginx/templates/logging.conf.template:/etc/nginx/templates/conf.d/logging.conf.template:ro
      - ./modsecurity-crs-nginx/nginx/templates/users.conf.template:/etc/nginx/templates/conf.d/users.conf.template:ro
      - ./modsecurity-crs-nginx/modsecurity-crs/rules/custom_rules.conf:/etc/modsecurity.d/owasp-crs/rules/custom_rules.conf:ro
      - ./modsecurity-crs-nginx/modsecurity-crs/templates/modsecurity-override.conf.template:/etc/nginx/templates/modsecurity.d/modsecurity-override.conf.template:ro
      - nginx_logs:/var/log/nginx
      - ./modsecurity-crs-nginx/nginx/logs/access.json.log:/tmp/access.json.log
      - ./modsecurity-crs-nginx/modsecurity-crs/logs/modsec_audit.json:/tmp/modsec_audit.json
      # User-specific configurations
      - ./modsecurity-crs-nginx/nginx/users:/etc/nginx/users:rw
      - ./modsecurity-crs-nginx/modsecurity-crs/users:/etc/modsecurity.d/owasp-crs/rules/users:rw
      # Docker socket for nginx reload from backend
      - /var/run/docker.sock:/var/run/docker.sock:ro

  backend-server:
    build: ./backend-server
    container_name: backend-server
    restart: always
    ports:
      - 3001:3001
    networks:
      - waf_network
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgres://waf:change_me@postgres:5432/waf_logs
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - APP_JWT_SECRET=${APP_JWT_SECRET}
    volumes:
      # Docker socket for controlling nginx container
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Access to user configuration files
      - ./modsecurity-crs-nginx/nginx/users:/app/nginx-configs:rw
      - ./modsecurity-crs-nginx/modsecurity-crs/users:/app/modsecurity-rules:rw
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - 3002:3000
    networks:
      - waf_network
    environment:
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - NEXT_PUBLIC_API_BASE_URL=http://backend-server:3001
    depends_on:
      - backend-server

  tenant-example:
    build: ./tenant-example
    container_name: tenant-example
    restart: always
    ports:
      - 3000:3000
    networks:
      - waf_network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=waf_logs
      - POSTGRES_USER=waf
      - POSTGRES_PASSWORD=change_me
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - waf_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U waf -d waf_logs']
      interval: 10s
      timeout: 5s
      retries: 5

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    restart: always
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./observability/fluent-bit/parsers_multiline.conf:/fluent-bit/etc/parsers_multiline.conf:ro
      - nginx_logs:/var/log/nginx:ro
      - ./modsecurity-crs-nginx/nginx/logs/access.json.log:/tmp/access.json.log:ro
      - ./modsecurity-crs-nginx/modsecurity-crs/logs/modsec_audit.json:/tmp/modsec_audit.json:ro
    networks:
      - waf_network
    depends_on:
      - waf-nginx
      - backend-server
      - tenant-example

networks:
  waf_network:
    driver: bridge

volumes:
  nginx_logs:
  pgdata:
